### ISSUE TITLE
Where is the Dockerfile that builds pagmo2/manylinux1_x86_64_with_deps?

### ISSUE THREAD

**Issue by soulmachine** [urschrei/minimal_cross_manylinux#1]
Hi urschrei,

Thank you for creating this wonderful repo, but one missing part is the Dockerfile that builds `pagmo2/manylinux1_x86_64_with_deps`

Can you share this Dockerfile so that I can learn how to build a manylinux image for cross? Thanks

**Comment by urschrei** [comment]
This is actually a better image:

https://github.com/urschrei/rdp/blob/master/Cross.toml

**Comment by soulmachine** [comment]
The image above is the original manylinux image, which is used by many Python projects, is it suitable for Rust projects?

**Comment by urschrei** [comment]
Yes very much so! It's being used to generate the Rust library used in my "simplification" Python package, for instance.
